apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass-secret-file
  literals:
  - password=redhat
resources:
  - dbkustomize11jan.yml
  - kustomization.yml