#apiVersion: v1
#kind: Pod

#	Set RS (Replica Set in code)
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  #name: "podwithimg"
  #name: "dbpod"
  #name: podlands
  name: "rspod1"
#			Equality Based
  #labels:
  #  region: IN
  #  dc: South
  #  app: Web
spec:
#			Set Based Selector
  selector:
    matchExpressions:
#      - wwe in Undertaker
    - { key: wwe , operator: In , values: ["South"] }
#  containers:
#    - name: "mywebcont"
#      image: "vimal13/apache-webserver-php"
    #- name: "mydb"
    #  image: "mysql"
      #env:
      #- name: MYSQL_ROOT_PASSWORD
      #  value: "redhat"