apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: erik-user-monitor-binding
  namespace: testing
subjects:
  - kind: User 
    name: erik
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: mymonitor-role
  apiGroup: rbac.authorization.k8s.io